# Obter código fonte
  - name: Checkout
    uses: actions/checkout@v4
    on: [workflow_dispatch]
    
# Setup up JDK
  - name: Set up Java
    uses: actions/setup-java@v4
    with:
    distribution: 'temurin’
    java-version: '21'
    
# Testes unitários
  - name: Build and unit tests
    run: mvn clean test

  # CodeQL
  - name: Initialize CodeQL
    uses: github/codeql-action/init@v4
    with:
    languages: java
  - name: Build for CodeQL Analysis
    run: mvn clean compile
  - name: Initialize CodeQL
    uses: github/codeql-action/analyze@v4
